// This file will be auto-generated by Supabase CLI
// Run: pnpm db:types

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            [key: string]: {
                Row: Record<string, unknown>
                Insert: Record<string, unknown>
                Update: Record<string, unknown>
            }
        }
        Views: {
            [key: string]: {
                Row: Record<string, unknown>
            }
        }
        Functions: {
            [key: string]: {
                Args: Record<string, unknown>
                Returns: unknown
            }
        }
    }
}
